### ISSUE TITLE
Rep is incomplete

### ISSUE THREAD

**Issue by bclements** [alias454/sec-airflow-ingester#1]
Hi This is fantastic work. Do you happen to have examples for actually using this? 

It seems like you are missing the main.tf, etc. from the root directory of the repo.

**Comment by alias454** [comment]
You should just be able to clone the repo then run terraform init from within the prod directory. It's covered in the Getting started section https://github.com/alias454/sec-airflow-ingester#Getting-Started. I did it that way so this can have multiple MWAA environments managed via the same repo.

**Comment by alias454** [comment]
Also, when you are asking about examples, are you referring to example Airflow DAGS or using Terraform to mange MWAA? I was using this to ingest data from a lot of different sources. Pulling data from an API and then dumping it to s3 for later consumption in Splunk was the primary goal. However, I was also able to push data into other services as needed.

**Comment by alias454** [comment]
Closing this. Feel free to reply if you have additional questions or open a new issue.
